version: "3"
services:
  node:
    container_name: backendnest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    expose:
      - "3000"
    links:
      - mysql
    depends_on:
      - mysql
      - redis-server
    networks:
      - febnine-net
  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: treegrow
      MYSQL_USER: junhyeong
      MYSQL_PASSWORD: password
    expose:
      - "3306"
    networks:
      - febnine-net

  redis-server:
    image: redis:latest
    container_name: redis-server
    hostname: redis-server
    ports:
      - "6379:6379"
    networks:
      - febnine-net

networks:
  febnine-net:
